packages:
  all:
    permissions:
      read: group
      group: wg-sierra-users
    compiler:
    - intel@19.0.3.199
    providers:
      mpi:
      - openmpi
      blas:
      - netlib-lapack
      lapack:
      - netlib-lapack
    variants: +mpi build_type=Release
  boost:
    version: [1.68.0]
    variants: cxxstd=14
  openmpi:
    version: [4.0.3]
    buildable: false
    externals:
    - spec: openmpi@4.0.3
      modules:
      - openmpi-intel/4.0.3
  intel-mpi:
    version: [2019.8.624]
    buildable: false
    externals:
    - spec: intel-mpi@2019.8.624
      modules:
      - intel-mpi/2019
  pkg-config:
    buildable: false
    externals:
    - spec: pkg-config@0.27.1
      prefix: /usr/bin/pkg-config
  openssl:
    version: [1.0.2]
    buildable: false
    externals:
    - spec: openssl@1.0.2
      prefix: /usr
  ncurses:
    version: [5.9]
    buildable: false
    externals:
    - spec: ncurses@5.9
      prefix: /usr
  binutils:
    version: [2.29.1]
  zlib:
    version: [1.2.7]
    buildable: false
    externals:
    - spec: zlib@1.2.7
      prefix: /usr
  bzip2:
    version: [1.0.6]
    buildable: false
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  m4:
    version: [1.4.16]
    buildable: false
    externals:
    - spec: m4@1.4.16
      prefix: /usr
  superlu:
    version: [4.3]
  netlib-lapack:
    version: [3.8.0]
