config:
  install_tree:
    root: $spack/opt/spack
    projections:
      all: ${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}
  module_roots:
    tcl: $spack/share/spack/modules
    lmod: $spack/share/spack/lmod
  build_stage:
  - $spack/var/spack/stage
  # Use single source cache per user to avoid unnecessary downloading across spack installations
  source_cache: $SPACK_MANAGER/.spack/downloads
  misc_cache: $SPACK_MANAGER/.spack/cache
  verify_ssl: true
  checksum: true
  dirty: false
  locks: true
  build_jobs: 16
