packages:
  all:
    compiler: [gcc]
    providers:
      mpi: [openmpi]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
    variants: build_type=Release
    target: [skylake]
  cmake:
    externals:
    - spec: cmake@3.12.2
      modules:
      - sierra-cmake/3.12.2
      prefix: /projects/sierra/linux_rh7/install/cmake/3.12.2/bin/cmake
  openmpi:
    externals:
    - spec: openmpi@4.0.2%gcc@7.2.0
      modules:
      - sierra-mpi/openmpi/4.0.2
      prefix: /projects/sierra/linux_rh7/SDK/mpi/openmpi/4.0.2-nvidia-9.2.148-RHEL7/
    buildable: false
  cuda:
    externals:
    - spec: "cuda@9.2.148%gcc@7.2.0 ^openmpi@4.0.2"
      modules:
      - sierra-compiler/nvidia/9.2.148
      prefix: /projects/sierra/linux_rh7/SDK/compilers/nvidia/cuda_9.2.148/
    buildable: false
  libtool:
    version: [2.4.6]
    compiler: [gcc@4.8.5]
  trilinos:
    version: [develop]
    variants: ~shared+exodus+tpetra+muelu+belos+ifpack2+amesos2+zoltan+stk+boost~superlu-dist+superlu+hdf5+zlib+pnetcdf+shards~hypre@master
      build_type=Release
