compilers:
  - compiler:
      spec: gcc@10.3.0
      paths:
        cc:  /opt/rh/gcc-toolset-10/root/usr/bin/gcc
        cxx: /opt/rh/gcc-toolset-10/root/usr/bin/g++
        f77: /opt/rh/gcc-toolset-10/root/usr/bin/gfortran
        fc:  /opt/rh/gcc-toolset-10/root/usr/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules:
      - PrgEnv-gnu-amd/8.5.0
      - gcc-native/10.3.0
      - libfabric
      environment: {}
      extra_rpaths:
       - /opt/rh/gcc-toolset-10/root/usr/lib64
