#  EXAMPLE: setting up a module pinned to a view defined in the 
#  environment
#  view:
#    daily:
#      root: /projects/wind/spack-manager/views/skybridge/daily
#  modules:
#    view_relative_modules:
#      enable: [tcl]
#      tcl:
#        all:
#          load: [sierra-compiler/intel/19.0.3, openmpi-intel/4.0]
#        blacklist_implicits: true
#        projections:
#          all: exawind-daily
#        hash_length: 0
#      roots:
#        tcl: /projects/wind/spack-manager/modules/skybridge/daily
#      use_view: daily
#      prefix_inspections:
#        bin:
#        - PATH
