compilers:
- compiler:
    environment: {}
    extra_rpaths:
    - /projects/sierra/linux_rh7/SDK/hwloc/lib
    - /projects/sierra/linux_rh7/SDK/mpi/openmpi/4.0.3-gcc-7.2.0-RHEL7/lib
    - /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL7/lib64
    - /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL7/lib
    flags: # {}
      cflags: -Wl,-rpath,/projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL7/lib64
      cxxflags: -Wl,-rpath,/projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL7/lib64
      fflags: -Wl,-rpath,/projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL7/lib64
    modules: [sierra-devel]
    operating_system: rhel7
    paths:
      cc: /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL7/bin/gcc
      cxx: /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL7/bin/g++
      f77: /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL7/bin/gfortran
      fc: /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL7/bin/gfortran
    spec: gcc@7.2.0
    target: x86_64
