compilers:
- compiler:
    environment: {}
    extra_rpaths:
    - /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL6/lib64
    - /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL6/lib
    - /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL6/libexec
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc: /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL6/bin/gcc
      cxx: /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL6/bin/g++
      f77: /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL6/bin/gfortran
      fc: /projects/sierra/linux_rh7/SDK/compilers/gcc/7.2.0-RHEL6/bin/gfortran
    spec: gcc@7.2.0
    target: x86_64
- compiler:
    spec: intel@19.0.3.199
    paths:
      cc: /projects/sierra/linux_rh7/SDK/compilers/intel/composer_xe_2019.3.199/compilers_and_libraries/linux/bin/intel64/icc
      cxx: /projects/sierra/linux_rh7/SDK/compilers/intel/composer_xe_2019.3.199/compilers_and_libraries/linux/bin/intel64/icpc
      f77: /projects/sierra/linux_rh7/SDK/compilers/intel/composer_xe_2019.3.199/compilers_and_libraries/linux/bin/intel64/ifort
      fc: /projects/sierra/linux_rh7/SDK/compilers/intel/composer_xe_2019.3.199/compilers_and_libraries/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
