packages:
  #pkg-config:
  #  buildable: false
  #  externals:
  #  - spec: pkg-config@0.29.2
  #    prefix: /usr/local/bin
  #python:
  #  version: [3.7.3]
  #  externals:
  #  - spec: python@3.7.3
  #    prefix: /usr
  #  - spec: python@2.7.16
  #    prefix: /usr
  all:
    #target: [x86_64]
    compiler: [apple-clang, gcc, clang]
    variants: build_type=Release
    providers:
      mpi: [openmpi, mpich]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
