packages:
  all:
    compiler: [gcc]
    providers:
      mpi: [openmpi]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
    variants: build_type=Release
    target: [x86_64]
  cmake:
    externals:
    - spec: cmake@3.20.0
      modules:
      - sierra-cmake/3.20.0
      prefix: /projects/sierra/linux_rh7/install/cmake/3.20.0/bin/cmake
  openmpi:
    externals:
    - spec: openmpi@4.0.5%gcc@7.2.0
      modules:
      - sierra-mpi/openmpi/4.0.5
      prefix: /projects/sierra/linux_rh7/SDK/mpi/openmpi/4.0.5-nvidia-11.2.1-RHEL7/
    buildable: false
  cuda:
    externals:
    - spec: cuda@11.2.1%gcc@7.2.0 ^openmpi@4.0.5
      modules:
      - sierra-compiler/nvidia/11.2.1
      prefix: /projects/sierra/linux_rh7/SDK/compilers/nvidia/cuda_11.2.1/
    buildable: false
  python:
    version: [3.6.10]
    buildable: false
    externals:
    - spec: python@2.7.10
      prefix: /projects/sierra/linux_rh7/install/Python/2.7/
    - spec: python@3.6.10
      modules:
      - sierra-python/3.6.10
